---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```r 
library(dplyr)
library(ggplot2)

activity = read.csv('activity.csv')
activity$date = as.Date(as.character(activity$date), format = '%Y-%m-%d')
activity$day = weekdays(activity$date)
act_clean = activity[!is.na(activity$steps), ]
```

## What is mean total number of steps taken per day?
total_steps_per_day = act_clean %>% group_by(date) %>% summarise(step = sum(steps))
ggplot(total_steps_per_day, aes(x = step)) + geom_histogram(col = 'black',fill = 'blue') + ggtitle('Total Steps per Day') + xlab('Steps') + ylab('Frequency') + ylim(0,10)
as.integer(mean(total_steps_per_day$step))
as.integer(median(total_steps_per_day$step))

## What is the average daily activity pattern?
steps_interval = act_clean %>% group_by(interval) %>% summarise(step = sum(steps))
ggplot(steps_interval, aes(x = interval, y = step)) + geom_line(col = 'black') + ggtitle('Average Number of Steps per Interval') + ylab('Average Number of Steps') + xlab('Interval')
steps_interval[which.max(steps_interval$step),]$interval



## Imputing missing values
sum(is.na(activity$steps))
x = act_clean %>% group_by(interval) %>% summarise(step = as.integer(mean(steps)))
y = activity[is.na(activity$steps),]
y1 = activity[!is.na(activity$steps),]

y = left_join(y, x, by = "interval")
y = y[,-1]
names(y)[4] = paste('steps')
y = y %>% select(4,1,2,3)
new = bind_rows(y1,y)

total_steps_per_day1 = new %>% group_by(date) %>% summarise(step = sum(steps))
ggplot(total_steps_per_day1, aes(x = step)) + geom_histogram(col = 'black',fill = 'blue') + ggtitle('Total Steps per Day') + xlab('Steps') + ylab('Frequency') + ylim(0,10)
as.integer(mean(total_steps_per_day1$step))
as.integer(median(total_steps_per_day1$step))



## Are there differences in activity patterns between weekdays and weekends?
new$Category = factor(ifelse(new$day %in% c('Saturday','Sunday'), 'Weekend', 'Weekday'))
average_step = new %>% group_by(interval, Category) %>% summarise(step = mean(steps))
ggplot(average_step, aes(x = interval, y = step)) + geom_line(col = 'blue') + ggtitle('Average Steps per Interval Based on Type of Day') + ylab('Average Number of Steps') + xlab('Interval') + facet_grid(~Category)


